//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVacationManagement.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHOTEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLHOTEL()
        {
            this.TBLHOTELREZERVASYON = new HashSet<TBLHOTELREZERVASYON>();
        }
    
        public int id { get; set; }
        public string isim { get; set; }
        public string konum { get; set; }
        public string ozellikler { get; set; }
        public string fotograf { get; set; }
        public Nullable<int> bir_kisilik_oda_sayisi { get; set; }
        public Nullable<decimal> bir_kisilik_oda_ucret { get; set; }
        public Nullable<int> iki_kisilik_oda_sayisi { get; set; }
        public Nullable<decimal> iki_kisilik_oda_ucret { get; set; }
        public Nullable<int> uc_kisilik_oda_sayisi { get; set; }
        public Nullable<decimal> uc_kisilik_oda_ucret { get; set; }
        public Nullable<int> dort_kisilik_oda_sayisi { get; set; }
        public Nullable<decimal> dort_kisilik_oda_ucret { get; set; }
        public string detaylar { get; set; }
        public Nullable<int> hotel_yetkilisi { get; set; }
        public Nullable<bool> durum { get; set; }
        public string fotograf2 { get; set; }
        public string fotograf3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHOTELREZERVASYON> TBLHOTELREZERVASYON { get; set; }
        public virtual TBLHOTELYETKILISI TBLHOTELYETKILISI { get; set; }
    }
}
