//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVacationManagement.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHOTELREZERVASYON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLHOTELREZERVASYON()
        {
            this.TBLMUSTERI1 = new HashSet<TBLMUSTERI>();
        }
    
        public int id { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<System.DateTime> baslangic { get; set; }
        public Nullable<System.DateTime> bitis { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<int> hotel { get; set; }
        public string kisi_sayisi { get; set; }
    
        public virtual TBLHOTEL TBLHOTEL { get; set; }
        public virtual TBLMUSTERI TBLMUSTERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMUSTERI> TBLMUSTERI1 { get; set; }
    }
}
