//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVacationManagement.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TBLMUSTERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUSTERI()
        {
            this.TBLHOTELREZERVASYON = new HashSet<TBLHOTELREZERVASYON>();
            this.TBLTURREZERVASYON1 = new HashSet<TBLTURREZERVASYON>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }

        public string kullanici_adi { get; set; }
        public string sifre { get; set; }
        public Nullable<int> tur_rezervasyonu { get; set; }
        public Nullable<int> hotel_rezervasyonu { get; set; }
        public Nullable<bool> durum { get; set; }
        public string telefon_numarasi { get; set; }
        public string rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHOTELREZERVASYON> TBLHOTELREZERVASYON { get; set; }
        public virtual TBLHOTELREZERVASYON TBLHOTELREZERVASYON1 { get; set; }
        public virtual TBLTURREZERVASYON TBLTURREZERVASYON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTURREZERVASYON> TBLTURREZERVASYON1 { get; set; }
    }
}
