//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVacationManagement.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLTUR()
        {
            this.TBLTURREZERVASYON = new HashSet<TBLTURREZERVASYON>();
        }
    
        public int id { get; set; }
        public string tur_basligi { get; set; }
        public string kalkis_yeri { get; set; }
        public string fotograf { get; set; }
        public string sure { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string detay { get; set; }
        public Nullable<int> tur_yetkilisi { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<int> kontenjan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTURREZERVASYON> TBLTURREZERVASYON { get; set; }
        public virtual TBLTURYETKILISI TBLTURYETKILISI { get; set; }
    }
}
